<?php
declare(strict_types=1);

/**
 * Additional Application Constants
 * Extended configuration values for the Uganda Results System
 */

// System Settings
define('SYSTEM_NAME', 'Uganda High School Results & Report Card System');
define('SYSTEM_SHORT_NAME', 'Uganda Results');
define('SYSTEM_VERSION', '1.0.0');
define('SYSTEM_AUTHOR', 'Uganda Education Technology');

// Academic Settings
define('CURRENT_ACADEMIC_YEAR', '2024');
define('ACADEMIC_YEAR_START_MONTH', 2); // February
define('ACADEMIC_YEAR_END_MONTH', 11);  // November

// Term Settings
define('TERMS_PER_YEAR', 3);
define('TERM_NAMES', ['Term 1', 'Term 2', 'Term 3']);

// Grade Settings
define('DEFAULT_MAX_MARK', 100);
define('DEFAULT_PASS_MARK', 50);

// O-Level Grade Boundaries (UCE)
define('UCE_GRADES', [
    'D1' => ['min' => 80, 'max' => 100, 'points' => 9, 'name' => 'Distinction 1'],
    'D2' => ['min' => 70, 'max' => 79, 'points' => 8, 'name' => 'Distinction 2'],
    'C3' => ['min' => 65, 'max' => 69, 'points' => 7, 'name' => 'Credit 3'],
    'C4' => ['min' => 60, 'max' => 64, 'points' => 6, 'name' => 'Credit 4'],
    'C5' => ['min' => 55, 'max' => 59, 'points' => 5, 'name' => 'Credit 5'],
    'C6' => ['min' => 50, 'max' => 54, 'points' => 4, 'name' => 'Credit 6'],
    'P7' => ['min' => 45, 'max' => 49, 'points' => 3, 'name' => 'Pass 7'],
    'P8' => ['min' => 40, 'max' => 44, 'points' => 2, 'name' => 'Pass 8'],
    'F9' => ['min' => 0, 'max' => 39, 'points' => 1, 'name' => 'Fail 9']
]);

// A-Level Grade Boundaries (UACE)
define('UACE_GRADES', [
    'A' => ['min' => 80, 'max' => 100, 'points' => 6, 'name' => 'A Grade'],
    'B' => ['min' => 70, 'max' => 79, 'points' => 5, 'name' => 'B Grade'],
    'C' => ['min' => 60, 'max' => 69, 'points' => 4, 'name' => 'C Grade'],
    'D' => ['min' => 50, 'max' => 59, 'points' => 3, 'name' => 'D Grade'],
    'E' => ['min' => 45, 'max' => 49, 'points' => 2, 'name' => 'E Grade'],
    'O' => ['min' => 40, 'max' => 44, 'points' => 1, 'name' => 'O Grade'],
    'F' => ['min' => 0, 'max' => 39, 'points' => 0, 'name' => 'F Grade']
]);

// Division Calculation (O-Level)
define('UCE_DIVISIONS', [
    'I' => ['min_points' => 28, 'min_passes' => 8, 'name' => 'Division I'],
    'II' => ['min_points' => 24, 'min_passes' => 8, 'name' => 'Division II'],
    'III' => ['min_points' => 20, 'min_passes' => 8, 'name' => 'Division III'],
    'IV' => ['min_points' => 16, 'min_passes' => 8, 'name' => 'Division IV'],
    'U' => ['min_points' => 0, 'min_passes' => 0, 'name' => 'Ungraded']
]);

// Core O-Level Subjects (Must Pass)
define('UCE_CORE_SUBJECTS', [
    'ENG' => 'English Language',
    'MATH' => 'Mathematics',
    'PHY' => 'Physics',
    'CHEM' => 'Chemistry',
    'BIO' => 'Biology',
    'HIST' => 'History',
    'GEOG' => 'Geography',
    'RE' => 'Religious Education'
]);

// A-Level Principal Pass Requirements
define('UACE_PRINCIPAL_PASSES', 2); // Minimum 2 principal passes
define('UACE_SUBSIDIARY_PASSES', 1); // Minimum 1 subsidiary pass

// Class Structure
define('O_LEVEL_CLASSES', ['Senior 1', 'Senior 2', 'Senior 3', 'Senior 4']);
define('A_LEVEL_CLASSES', ['Senior 5', 'Senior 6']);
define('CLASS_CAPACITY', 40); // Default students per class

// Common Streams
define('O_LEVEL_STREAMS', ['A', 'B', 'C', 'D']);
define('A_LEVEL_STREAMS', ['PCM', 'PCB', 'HEG', 'HGL', 'MEG']);

// Assessment Types
define('ASSESSMENT_TYPES', [
    'BOT' => ['name' => 'Beginning of Term', 'weight' => 30, 'is_exam' => false],
    'MID' => ['name' => 'Mid Term Exam', 'weight' => 30, 'is_exam' => true],
    'EOT' => ['name' => 'End of Term Exam', 'weight' => 40, 'is_exam' => true]
]);

// Report Card Settings
define('REPORT_CARD_FOOTER', 'This report card is generated by the Uganda Results System.');
define('NEXT_TERM_MESSAGE', 'Next term begins on');
define('HEADTEACHER_SIGNATURE', 'Head Teacher\'s Signature');
define('STUDENT_SIGNATURE', 'Student\'s Signature');

// File Upload Settings
define('ALLOWED_IMAGE_TYPES', ['image/jpeg', 'image/png', 'image/gif']);
define('ALLOWED_DOCUMENT_TYPES', ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document']);
define('MAX_LOGO_SIZE', 2 * 1024 * 1024); // 2MB
define('MAX_AVATAR_SIZE', 1 * 1024 * 1024); // 1MB
define('MAX_DOCUMENT_SIZE', 10 * 1024 * 1024); // 10MB

// Email Settings
define('SYSTEM_EMAIL', 'noreply@uganda-results.com');
define('SUPPORT_EMAIL', 'support@uganda-results.com');
define('ADMIN_EMAIL', 'admin@uganda-results.com');

// Notification Settings
define('NOTIFICATION_TYPES', [
    'MARKS_ENTERED' => 'Marks Entered',
    'REPORT_GENERATED' => 'Report Card Generated',
    'STUDENT_REGISTERED' => 'Student Registered',
    'USER_CREATED' => 'User Account Created',
    'PASSWORD_RESET' => 'Password Reset',
    'SYSTEM_BACKUP' => 'System Backup'
]);

// Backup Settings
define('BACKUP_RETENTION_DAYS', 30);
define('AUTO_BACKUP_ENABLED', true);
define('BACKUP_SCHEDULE', 'daily'); // daily, weekly, monthly

// Performance Settings
define('CACHE_ENABLED', false);
define('CACHE_LIFETIME', 3600); // 1 hour
define('DEBUG_MODE', true); // Set to false in production

// Regional Settings
define('DEFAULT_TIMEZONE', 'Africa/Kampala');
define('DEFAULT_CURRENCY', 'UGX');
define('DEFAULT_LOCALE', 'en_UG');
define('DATE_FORMAT', 'd/m/Y');
define('DATETIME_FORMAT', 'd/m/Y H:i');

// Security Settings
define('LOGIN_ATTEMPTS_LIMIT', 5);
define('LOGIN_LOCKOUT_DURATION', 900); // 15 minutes
define('SESSION_TIMEOUT', 7200); // 2 hours
define('CSRF_TOKEN_LIFETIME', 3600); // 1 hour

// API Settings
define('API_VERSION', 'v1');
define('API_RATE_LIMIT', 1000); // requests per hour
define('API_ENABLED', false); // Enable API access

// Theme Settings
define('DEFAULT_THEME', 'light');
define('AVAILABLE_THEMES', ['light', 'dark']);
define('THEME_COLORS', [
    'primary' => '#0ea5e9',
    'secondary' => '#6b7280',
    'success' => '#10b981',
    'danger' => '#ef4444',
    'warning' => '#f59e0b',
    'info' => '#3b82f6'
]);

// Export Settings
define('EXPORT_FORMATS', ['PDF', 'Excel', 'CSV']);
define('PDF_ORIENTATION', 'portrait'); // portrait or landscape
define('PDF_SIZE', 'A4');
define('EXCEL_FORMAT', 'xlsx');

// System Health Check URLs
define('HEALTH_CHECK_URLS', [
    'database' => '/health/database',
    'storage' => '/health/storage',
    'email' => '/health/email'
]);

// Feature Flags
define('FEATURES', [
    'STUDENT_PORTAL' => true,
    'PARENT_PORTAL' => false,
    'SMS_NOTIFICATIONS' => false,
    'EMAIL_NOTIFICATIONS' => true,
    'BULK_IMPORT' => true,
    'ADVANCED_ANALYTICS' => false,
    'MULTI_LANGUAGE' => false,
    'API_ACCESS' => false
]);

// Uganda Districts (for school location)
define('UGANDA_REGIONS', [
    'Central' => ['Kampala', 'Wakiso', 'Mukono', 'Mpigi', 'Luwero', 'Masaka', 'Mubende'],
    'Eastern' => ['Jinja', 'Mbale', 'Soroti', 'Tororo', 'Iganga', 'Busia', 'Pallisa'],
    'Northern' => ['Gulu', 'Lira', 'Arua', 'Kitgum', 'Pader', 'Apac', 'Moroto'],
    'Western' => ['Mbarara', 'Kasese', 'Hoima', 'Kabale', 'Bushenyi', 'Ntungamo', 'Rukungiri']
]);

// Uganda School Types
define('SCHOOL_TYPES', [
    'GOVERNMENT' => 'Government School',
    'PRIVATE' => 'Private School',
    'COMMUNITY' => 'Community School',
    'FAITH_BASED' => 'Faith-Based School'
]);

// Student Status Types
define('STUDENT_STATUSES', [
    'ACTIVE' => 'Active',
    'GRADUATED' => 'Graduated',
    'TRANSFERRED' => 'Transferred',
    'DROPPED' => 'Dropped Out',
    'SUSPENDED' => 'Suspended'
]);

// User Roles with Descriptions
define('USER_ROLES', [
    'SUPER_ADMIN' => ['name' => 'Super Administrator', 'description' => 'Full system access'],
    'SCHOOL_ADMIN' => ['name' => 'School Administrator', 'description' => 'School management access'],
    'STAFF' => ['name' => 'Teaching Staff', 'description' => 'Class and subject management'],
    'STUDENT' => ['name' => 'Student', 'description' => 'View results and reports']
]);

// Default Passwords (for development only)
if (DEBUG_MODE) {
    define('DEFAULT_ADMIN_PASSWORD', 'admin123');
    define('DEFAULT_STUDENT_PASSWORD', 'student123');
    define('DEFAULT_STAFF_PASSWORD', 'staff123');
}

// System Messages
define('SYSTEM_MESSAGES', [
    'welcome' => 'Welcome to the Uganda High School Results & Report Card System',
    'maintenance' => 'System is currently under maintenance. Please try again later.',
    'error' => 'An error occurred. Please contact system administrator.',
    'success' => 'Operation completed successfully.',
    'permission_denied' => 'You do not have permission to access this resource.'
]);

// Version History
define('VERSION_HISTORY', [
    '1.0.0' => ['date' => '2024-01-01', 'description' => 'Initial release'],
]);

// Development Settings
if (DEBUG_MODE) {
    define('SHOW_ERRORS', true);
    define('LOG_QUERIES', true);
    define('DEMO_MODE', true);
} else {
    define('SHOW_ERRORS', false);
    define('LOG_QUERIES', false);
    define('DEMO_MODE', false);
}
